trigger:
  - master

pool:
  name: Default

steps:
  - script: chmod +x gradlew
    displayName: 'Dar permisos a Gradle'

  - script: ./gradlew clean build
    displayName: 'Build proyecto'

  # Tests normales
  - script: ./gradlew test
    displayName: 'Run tests'

  # Mutation testing con PIT
  - script: ./gradlew pitest
    displayName: 'Mutation testing (PIT)'