services:

  agente-build:
    build:
     context: ./agente-azure
     dockerfile: build.Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - AZP_POOL=Build
    networks:
      - jmeter-net

  agente-jmeter:
    build:
      context: ./agente-azure
      dockerfile: jmeter.Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - AZP_POOL=JMeter
    depends_on:
      - influxdb
    networks:
      - jmeter-net

  influxdb:
    image: influxdb:1.8
    container_name: influxdb-jmeter
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=jmeter
    networks:
      - jmeter-net

  grafana:
    image: grafana/grafana
    container_name: grafana-jmeter
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/dashboards:/var/lib/grafana/dashboards
    networks:
      - jmeter-net

networks:
  jmeter-net: